import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html
      className={`${GeistSans.variable} ${GeistMono.variable} scrollbar-thin scrollbar-track-gray scrollbar-thumb-gray-darkGray text-white `}
      lang="en"
    >
      <body className="bg-black">{children}</body>
    </html>
  )
}
