import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html
      className={`scrollbar-thin scrollbar-track-gray scrollbar-thumb-gray-darkGray text-white  bg-black dark`}
      lang="en"
    >
      <body className="bg-black">{children}</body>
    </html>
  )
}
